In [ ]:
#张量数据的创建、变形、运算、合并、切片、数据类型转换、节约内存的存储方式

In [1]:
import torch

In [2]:
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [4]:
x.shape

torch.Size([12])

In [5]:
x.numel()

12

In [9]:
X = x.reshape(2, 6)

In [10]:
X

tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]])

In [12]:
x.shape

torch.Size([12])

In [13]:
x.numel()

12

In [14]:
X.shape

torch.Size([2, 6])

In [15]:
X.numel()

12

In [16]:
torch.zeros((2, 3, 4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [17]:
torch.ones((3, 2, 8))

tensor([[[1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1.]]])

In [18]:
torch.randn(3,4)

tensor([[ 0.3329,  0.6192, -0.5084,  0.2335],
        [ 1.7531,  0.6405,  0.2691,  0.8273],
        [ 0.9101,  1.0316, -1.6753,  1.2460]])

In [24]:
x = torch.tensor([[2, 1, 3, 4],[6, 5, 4, 3]])
x

tensor([[2, 1, 3, 4],
        [6, 5, 4, 3]])

In [25]:
x.shape

torch.Size([2, 4])

In [31]:
x = torch.tensor([2, 2, 2, 2])

In [32]:
x.shape

torch.Size([4])

In [33]:
y = torch.tensor([1, 2, 3, 4])

In [34]:
x+y

tensor([3, 4, 5, 6])

In [35]:
x-y

tensor([ 1,  0, -1, -2])

In [36]:
x**y

tensor([ 2,  4,  8, 16])

In [37]:
x*y

tensor([2, 4, 6, 8])

In [38]:
x/y

tensor([2.0000, 1.0000, 0.6667, 0.5000])

In [39]:
torch.exp(y)

tensor([ 2.7183,  7.3891, 20.0855, 54.5981])

In [40]:
x==y

tensor([False,  True, False, False])

In [41]:
x

tensor([2, 2, 2, 2])

In [42]:
y

tensor([1, 2, 3, 4])

In [45]:
torch.cat((x,y),dim=0)

tensor([2, 2, 2, 2, 1, 2, 3, 4])

In [47]:
X = torch.arange(12).reshape(3, 4)

In [48]:
Y = torch.tensor([[9, 8, 7, 6],
                  [6, 5, 4, 3],
                  [4, 3, 2, 1]])

In [49]:
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [50]:
Y

tensor([[9, 8, 7, 6],
        [6, 5, 4, 3],
        [4, 3, 2, 1]])

In [51]:
X.shape

torch.Size([3, 4])

In [52]:
Y.shape

torch.Size([3, 4])

In [53]:
torch.cat((X,Y))

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [ 9,  8,  7,  6],
        [ 6,  5,  4,  3],
        [ 4,  3,  2,  1]])

In [55]:
torch.cat((X,Y),dim=1).sum()

tensor(124)

In [56]:
x=torch.arange(3).reshape(3,1)

In [69]:
y = torch.tensor([1,2]).reshape(1,2)

In [70]:
x

tensor([[0],
        [1],
        [2]])

In [71]:
y

tensor([[1, 2]])

In [72]:
x.shape

torch.Size([3, 1])

In [73]:
y.shape

torch.Size([1, 2])

In [74]:
x+y

tensor([[1, 2],
        [2, 3],
        [3, 4]])

In [75]:
Z = torch.cat((X,Y))

In [76]:
Z

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [ 9,  8,  7,  6],
        [ 6,  5,  4,  3],
        [ 4,  3,  2,  1]])

In [81]:
Z[2:5]

tensor([[ 8,  9, 10, 11],
        [ 9,  8,  7,  6],
        [ 6,  5,  4,  3]])

In [84]:
Z[2:5][0:2]

tensor([[ 8,  9, 10, 11],
        [ 9,  8,  7,  6]])

In [85]:
Z[2:5, 1:3]

tensor([[ 9, 10],
        [ 8,  7],
        [ 5,  4]])

In [86]:
x_num = X.numpy()

In [87]:
x_num

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [88]:
type(x_num),type(X)

(numpy.ndarray, torch.Tensor)

In [92]:
a=torch.tensor([3.5])

In [93]:
a

tensor([3.5000])

In [95]:
type(float(a)),type(a.item()),type(int(a))

(float, float, int)

In [96]:
int(a)

3

In [97]:
x

tensor([[0],
        [1],
        [2]])

In [98]:
y

tensor([[1, 2]])

In [99]:
x = torch.tensor([4,5,6])

In [100]:
x

tensor([4, 5, 6])

In [101]:
y = torch.arange(3)

In [114]:
y

tensor([ 8, 11, 14])

In [115]:
id(y)

140655522565712

In [116]:
before = id(y)

In [117]:
y+=x

In [118]:
before == id(y)

True

In [119]:
y

tensor([12, 16, 20])