In [1]:
import torch

In [2]:
x = torch.arange(4)

In [3]:
x

tensor([0, 1, 2, 3])

In [4]:
x[3]

tensor(3)

In [5]:
len(x)

4

In [8]:
x.size()

torch.Size([4])

In [9]:
x.shape

torch.Size([4])

In [10]:
x.numel()

4

In [11]:
x = torch.arange(20).reshape(5,4)

In [12]:
x

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

In [13]:
x.T

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

In [14]:
y = x.clone()

In [15]:
x==y

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

In [25]:
#形状相同的张量运算为元素间运算
#张量与标量运算也是元素间运算

In [22]:
x*y

tensor([[  0,   1,   4,   9],
        [ 16,  25,  36,  49],
        [ 64,  81, 100, 121],
        [144, 169, 196, 225],
        [256, 289, 324, 361]])

In [23]:
x+2

tensor([[ 2,  3,  4,  5],
        [ 6,  7,  8,  9],
        [10, 11, 12, 13],
        [14, 15, 16, 17],
        [18, 19, 20, 21]])

In [24]:
x*2

tensor([[ 0,  2,  4,  6],
        [ 8, 10, 12, 14],
        [16, 18, 20, 22],
        [24, 26, 28, 30],
        [32, 34, 36, 38]])

In [27]:
x

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

In [33]:
x=torch.arange(20,dtype=torch.float32).reshape(5,4)

In [34]:
x

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])

In [35]:
x.mean()

tensor(9.5000)

In [36]:
x.sum()/x.numel()

tensor(9.5000)

In [37]:
x.sum(dim=0)

tensor([40., 45., 50., 55.])

In [38]:
x.sum(dim=1)

tensor([ 6., 22., 38., 54., 70.])

In [39]:
x.cumsum(axis=0)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  6.,  8., 10.],
        [12., 15., 18., 21.],
        [24., 28., 32., 36.],
        [40., 45., 50., 55.]])

In [46]:
x=torch.arange(4,dtype=torch.float32)

In [47]:
x

tensor([0., 1., 2., 3.])

In [48]:
y = torch.tensor([3.0, 5.0, 1.0, 2.0])

In [49]:
y

tensor([3., 5., 1., 2.])

In [50]:
torch.dot(x,y)

tensor(13.)

In [51]:
x

tensor([0., 1., 2., 3.])

In [53]:
A=torch.arange(12,dtype = torch.float32).reshape(3,4)

In [54]:
A

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [55]:
x

tensor([0., 1., 2., 3.])

In [56]:
torch.mv(A,x)

tensor([14., 38., 62.])

In [57]:
B = torch.ones(4,3,dtype = torch.float32)

In [58]:
torch.mm(A,B)

tensor([[ 6.,  6.,  6.],
        [22., 22., 22.],
        [38., 38., 38.]])

In [59]:
torch.mm(B,A)

tensor([[12., 15., 18., 21.],
        [12., 15., 18., 21.],
        [12., 15., 18., 21.],
        [12., 15., 18., 21.]])

In [60]:
x

tensor([0., 1., 2., 3.])

In [64]:
x.norm()

tensor(3.7417)

In [65]:
torch.norm(x)

tensor(3.7417)

In [66]:
torch.abs(x).sum()

tensor(6.)