In [1]:
import numpy as np

In [3]:
from matplotlib_inline import backend_inline

In [4]:
def f(x):
    return 3*x**2-4*x

In [6]:
def numerical_lim(f,x,h):
    return (f(x+h)-f(x))/h

In [7]:
h=0.1

In [9]:
for i in range(5):
    print(f'h={h:.5f},numerical limit={numerical_lim(f,1,h):.5f}')
    h*=0.1

h=0.10000,numerical limit=2.30000
h=0.01000,numerical limit=2.03000
h=0.00100,numerical limit=2.00300
h=0.00010,numerical limit=2.00030
h=0.00001,numerical limit=2.00003


In [10]:
def use_svg_display():
    backend_inline.set_matplotlib_formats('svg')

In [11]:
from matplotlib import pyplot as plt

In [12]:
def set_figsize(figsize=(3.5, 2.5)):
    use_svg_display()
    plt.rcParams['figure.figsize']=figsize

In [13]:
def set_axes(axes, xlabel, ylabel, xlim, ylim, xscale, yscale, legend):
    axes.set_xlabel(xlabel)
    axes.set_ylabel(ylabel)
    axes.set_xscale(xscale)
    axes.set_yscale(yscale)
    axes.set_xlim(xlim)
    axes.set_ylim(ylim)
    if legend:
        axes.legend(legend)
    axes.grid()

In [14]:
import torch

In [15]:
x=torch.arange(4.0)

In [16]:
x

tensor([0., 1., 2., 3.])

In [17]:
x.grad

In [18]:
x.grad

In [19]:
print(x.grad)

None


In [27]:
x.requires_grad_(True)

tensor([0., 1., 2., 3.], requires_grad=True)

In [28]:
x.grad

In [29]:
x.requires_grad

True

In [30]:
y=2*torch.dot(x,x)

In [31]:
y

tensor(28., grad_fn=<MulBackward0>)

In [32]:
y.backward()

In [33]:
y

tensor(28., grad_fn=<MulBackward0>)

In [34]:
x.grad

tensor([ 0.,  4.,  8., 12.])

In [35]:
x.grad.zero_()

tensor([0., 0., 0., 0.])

In [36]:
x.grad

tensor([0., 0., 0., 0.])

In [37]:
y=x.sum()

In [38]:
y.backward()

In [39]:
x.grad

tensor([1., 1., 1., 1.])

In [40]:
x.grad.zero_()

tensor([0., 0., 0., 0.])

In [41]:
y=torch.dot(x,x)

In [42]:
y=y*2

In [43]:
y.backward()

In [44]:
x.grad

tensor([ 0.,  4.,  8., 12.])

In [45]:
x.grad.zero_()

tensor([0., 0., 0., 0.])

In [46]:
y=x*x

In [47]:
u=y.detach()

In [48]:
z=u*x

In [49]:
z.sum().backward()

In [50]:
x.grad

tensor([0., 1., 4., 9.])

In [64]:
x.grad.zero_()

tensor([0., 0., 0., 0.])

In [65]:
y=x*x

In [66]:
z=y*x

In [67]:
z.sum().backward()

In [68]:
x.grad

tensor([ 0.,  3., 12., 27.])