In [1]:
import torch
from torch import nn

In [2]:
net = nn.Sequential(nn.Linear(4, 8), nn.ReLU(), nn.Linear(8, 1))
X = torch.rand((2, 4))
net(X)

tensor([[-0.3991],
        [-0.4570]], grad_fn=<AddmmBackward0>)

In [3]:
print(net[2].state_dict())

OrderedDict([('weight', tensor([[-0.0730,  0.2193, -0.1753, -0.2574, -0.1671,  0.0711,  0.3094, -0.2959]])), ('bias', tensor([-0.2302]))])


In [8]:
print(net[2].weight.data)

tensor([[-0.0730,  0.2193, -0.1753, -0.2574, -0.1671,  0.0711,  0.3094, -0.2959]])


In [9]:
print(net[2].bias.data)

tensor([-0.2302])


In [11]:
print(net[2].bias.grad)

None


In [12]:
print(*[(name, param.shape) for name,param in net[0].named_parameters()])

('weight', torch.Size([8, 4])) ('bias', torch.Size([8]))


In [13]:
print(*[(name,param.shape) for name,param in net.named_parameters()])

('0.weight', torch.Size([8, 4])) ('0.bias', torch.Size([8])) ('2.weight', torch.Size([1, 8])) ('2.bias', torch.Size([1]))


In [14]:
net[2].state_dict()

OrderedDict([('weight',
              tensor([[-0.0730,  0.2193, -0.1753, -0.2574, -0.1671,  0.0711,  0.3094, -0.2959]])),
             ('bias', tensor([-0.2302]))])

In [17]:
net[2].state_dict()['bias']

tensor([-0.2302])

In [18]:
net.state_dict()['2.bias']

tensor([-0.2302])

In [19]:
net[2].bias.data

tensor([-0.2302])

In [20]:
def init_ones(m):
    if type(m)==nn.Linear:
        nn.init.ones_(m.weight)
        nn.init.ones_(m.bias)
    
def init_normal(m):
    if type(m)==nn.Linear:
        nn.init.normal_(m.weight, mean=0, std=0.01)
        nn.init.zeros_(m.bias)


In [21]:
net

Sequential(
  (0): Linear(in_features=4, out_features=8, bias=True)
  (1): ReLU()
  (2): Linear(in_features=8, out_features=1, bias=True)
)

In [22]:
net.apply(init_ones)

Sequential(
  (0): Linear(in_features=4, out_features=8, bias=True)
  (1): ReLU()
  (2): Linear(in_features=8, out_features=1, bias=True)
)

In [23]:
net[0].weight.data

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [24]:
net[0].bias.data

tensor([1., 1., 1., 1., 1., 1., 1., 1.])

In [25]:
net.apply(init_normal)

Sequential(
  (0): Linear(in_features=4, out_features=8, bias=True)
  (1): ReLU()
  (2): Linear(in_features=8, out_features=1, bias=True)
)

In [26]:
net[0].weight.data

tensor([[ 0.0143, -0.0001, -0.0107, -0.0041],
        [ 0.0051, -0.0056, -0.0199,  0.0189],
        [-0.0063,  0.0048,  0.0047,  0.0142],
        [ 0.0023, -0.0022,  0.0152,  0.0068],
        [-0.0012, -0.0026,  0.0073, -0.0067],
        [-0.0044,  0.0113, -0.0165, -0.0058],
        [-0.0039,  0.0094, -0.0073,  0.0176],
        [-0.0338, -0.0052, -0.0085,  0.0030]])

In [27]:
net[2].apply(init_ones)

Linear(in_features=8, out_features=1, bias=True)

In [28]:
net[2].weight

Parameter containing:
tensor([[1., 1., 1., 1., 1., 1., 1., 1.]], requires_grad=True)

In [29]:
net[2].weight.data += 1

In [30]:
net[2].weight.data

tensor([[2., 2., 2., 2., 2., 2., 2., 2.]])